spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jwt:
  secret: ${JWT_SECRET:DefaultDevSecretThatIsAtLeast32CharsLongHdP0UvXtFbHyGZpR0akLQnW9N8FYeMbTpC7rXz5VgqJm3sLkHdP0UvXtFbHyGZpR0}
  expirationMs: ${JWT_EXPIRATION_MS:3600000}