# src/main/resources/application.yml
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update            # Automatically update schema (for development)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT settings (loaded from environment via JwtUtils)
jwt:
  secret: ${JWT_SECRET}           # e.g., set in .env
  expirationMs: ${JWT_EXPIRATION_MS} # e.g., 3600000 (1h)

logging:
  level:
    com.example.taskmanager: DEBUG
