# src/main/resources/application.yml
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update            # Automatically update schema (for development)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
